Bugfixes for Issue #10 and #11
scriptcoded/sql-highlight pull request #12
Opened 2020-10-05 11:55 UTC by ggerhard

Proposed bugfixes for Issues #10 and #11 :

#10  : Keywords at the end of a string will be cut off if they are not followed by a SPLIT_CHAR. 
Quick fix: added EOL as alternative

#11 : Matches inside of other matches (e.g. strings) will be appended as duplicate substring at the end of the original match
Proposed fix: filter/remove nested matches

2020-10-05 19:20 UTC, scriptcoded requested changes
Thanks for submitting your improvements! I haven't had a lot of time to fix these issues.

I looked through your code, and your solutions look solid. Would you mind removing semicolons (my bad for not having a styleguide/linter) before I merge your changes?

2020-10-05 19:33 UTC, scriptcoded requested changes

2020-10-05 19:33 UTC, scriptcoded commented on index.js
> +     }
There also seems to be some indentation issues here. I'll make sure to get a linter set up asap...

2020-10-06 08:33 UTC, ggerhard commented
Glad to be of help! I removed the semicolons (Java habit ;)) and improved the indentation, I hope it's ok now.

2020-10-06 12:27 UTC, scriptcoded commented
Thank you for the fixes, and happy Hacktober! :tada:

2020-10-06 12:28 UTC, scriptcoded approved these changes

2020-10-06 12:28 UTC, merged