docs(TypeScript): add TypeScript type definitions
scriptcoded/sql-highlight pull request #28
Opened 2021-08-28 17:13 UTC by igoro00

add TypeScript definitions to library's API
for better integration in TS projects and better DX(autocompletion
and auto-importing)

2021-08-28 17:21 UTC, igoro00 commented
sorry that there are no tests for TS typings but I don't know how to implement them correctly

2021-08-30 18:32 UTC, scriptcoded requested changes
Hey, thanks for the PR!

Sorry, didn't notice you raised it as I got a bunch of notifications from https://github.com/pomahtuk/sequilize-highlight.

I'll have a closer look at the typings as well as tests tomorrow if I get the time. I took a quick peek and for now I just have a few formatting wishes :)

Another thing I'll just put out there. Should the options interface be inside the module declaration, and should there be a namespace? I usually don't write a lot of typings, so I'm not sure about the best approach. I want to be a bit careful here as modifying changes after the fact most likely would mean a breaking change, or at least potentially breaking users build pipelines.

2021-08-30 18:32 UTC, scriptcoded commented on lib/index.d.ts
> +}
Formatting according to my other TypeScript projects as well as capitalizing `highlightOptions`.

```suggestion
export interface HighlightOptions {
  html?: boolean;
  classPrefix?: string;
  colors?: {
    keyword: string;
    function: string;
    number: string;
    string: string;
    special: string;
    bracket: string;
    clear: string;
  };
}

declare module 'sql-highlight' {
  export function highlight(sqlString: string, options?: HighlightOptions): string
}

```

2021-08-31 12:15 UTC, igoro00 commented
That interface should definitely be inside the module, my bad.
I don't know about the namespace though. I don't have much experience with writing declaration files either(I usually just write the code in TypeScript and the compiler generates definitions for me) but I looked at .d.ts files of many libraries that I currently use in my project(typegraphql+apollo+fastify and their dependencies) and >90% of them either top-level export everything or `
declare module 'name-of-the-module' {
  //all types exported here
}
`.

Also DefinitelyTyped in their [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) says that you should just `declare module`. They don't mention namespaces at all.

2021-08-31 12:35 UTC, igoro00 commented
>  I want to be a bit careful here as modifying types after the fact most likely would mean a breaking change, or at least potentially breaking users build pipelines.

I think as long type declarations match the code and we test if it builds correctly with a test project we should be perfectly fine. For example I tested right now(manually ofc) if moving the HighlightOptions interface to the module would break my project(I'm already using that .d.ts in my code by just pasting the file in node_modules) and typescript just didn't care. It built just fine and intellisence didn't change.

2021-08-31 13:16 UTC, scriptcoded requested changes
@igoro00 In that case I think these changes should be pretty much sufficient. If you can just add `"types": "./lib/index.d.ts"` to `package.json` (right after `"main": "./lib/index.js"`) so that NPM others can pick it up I'm happy to merge your changes.

As for testing the types I might add linting in the future, and perhaps also check that the types are updated if the exposed API is changed, if possible. I'll leave that be for now though.

Thanks for contributing!

2021-08-31 16:08 UTC, merged